### ISSUE TITLE
CustomCSS affects not only HTML mails but also text mails

### ISSUE THREAD

**Issue by fermiongithub** [GrantEdwards/CustomCSS#2]
Hi Grant.

CustomCSS affects not only HTML mails but also pure text mails in the composer.

Example:

body { max-width: 35em }

It would be great if you could limit the effect to HTML mails.

What do you think about this suggestion?

Best, Andreas

**Comment by GrantEdwards** [comment]
I think that sounds like an excellent suggestion, but I have no clue how to do that.  I'll do some research, but if you have any ideas please let me know.

**Comment by Betterbird** [comment]
You want to distinguish whether you're in a plaintext compose or HTML compose?

**Comment by GrantEdwards** [comment]
> You want to distinguish whether you're in a plaintext compose or HTML compose?

yes

**Comment by Betterbird** [comment]
WebExtension or WE experiment?

In the former case, get the compose body, I assume it won't be returned 
as HTML if it's a plaintext composition. In the latter case, the window 
carries a global gComposeType or some such. I'd have to look.

**Comment by Betterbird** [comment]
https://webextension-api.thunderbird.net/en/latest/compose.html#compose-composedetails

There is a parameter isPlainText.

For the experiment:
gMsgCompose.composeHTML

**Comment by GrantEdwards** [comment]
> WebExtension or WE experiment?

I don't know.  Extension, I think.  It shows up under "Extensions" in the Add-ons Manager.

> In the former case, get the compose body, I assume it won't be returned as HTML if it's a plaintext composition. In the latter case, the window carries a global gComposeType or some such. I'd have to look.

**Comment by GrantEdwards** [comment]
> https://webextension-api.thunderbird.net/en/latest/compose.html#compose-composedetails There is a parameter isPlainText.

That page appears to describe a describe a composeDetails object type which has an attribute named isPlainText. How does one obtain such an object within a javascript file registered via browser.composeScripts.register()?

 > For the experiment: gMsgCompose.composeHTML

I'm currently assuming it's an extension rather than an experiment. I don't see anything mentioning "experiment" in the manifest.

**Comment by Betterbird** [comment]
It's not an experiment, I looked at the code.

Looks like your JS is injected into the compose window's document. You 
could just get the body and check whether it's HTML for a plaintext 
composition with stuff like pre-wrap or so or a "normal" HTML 
composition.

You can use our add-on ThunderHTMLedit to see how the bodies differ.

**Comment by GrantEdwards** [comment]
> It's not an experiment, I looked at the code.

Yep, that's what I've decided.

> Looks like your JS is injected into the compose window's document.

Right.

> You could just get the body and check whether it's HTML for a plaintext composition with stuff like pre-wrap or so or a "normal" HTML composition. You can use our add-on ThunderHTMLedit to see how the bodies differ.

For an HTML message there's a global object 'document' with a type of HTMLDocument. Once I figure out how to compose a plaintext message, I'm going compare the 'document' object type/attributes.

**Comment by Betterbird** [comment]
Shift+New, Shift+Reply, etc.

**Comment by GrantEdwards** [comment]
> WebExtension or WE experiment? In the former case, get the compose body, I assume it won't be returned as HTML if it's a plaintext composition.

Nope, when composing in "plaintext" mode, the 'document' is an HTMLDocument object same as when composing in HTML. AFAICT, the only difference is that the default  style for the <body> element is: it uses a fixed-width font  with pre-wrap enabled and a width of 72ch.

**Comment by Betterbird** [comment]
If you don't want to compare on pre-wrap, you need to get the compose 
details and the isPlainText flag.

Look at other add-ons and how they get those compose details.

**Comment by GrantEdwards** [comment]
> If you don't want to compare on pre-wrap,

I don't like it, but that's what I'm going to have to do: check the whitespace, font, and width style attributes for the body element.

> you need to get the compose details and the isPlainText flag. Look at other add-ons and how they get those compose details.

Unless somebody points me to a relevant add-on, I've given up on that approach. There's no practical way to search other addons short of manually downloading and unpacking all of them.

**Comment by Betterbird** [comment]
> > WebExtension or WE experiment? In the former case, get the compose body, I assume it won't be returned as HTML if it's a plaintext composition.
> 
> Nope, when composing in "plaintext" mode, the 'document' is an HTMLDocument object same as when composing in HTML. AFAICT, the only difference is that the default style for the element is: it uses a fixed-width font with pre-wrap enabled and a width of 72ch.

There is a misunderstanding here. I never suggested that the document would be anything but HTML, that's why I said in https://github.com/GrantEdwards/CustomCSS/issues/2#issuecomment-1741784408: _"You could just get the body and check whether it's **HTML for a plaintext** composition with stuff like pre-wrap or so or a "normal" HTML composition"_.

_"get the compose body"_ was referring to this API/data structure which delivers the `body`. I was on the phone before and there I can't write lengthy comments with references:
https://webextension-api.thunderbird.net/en/latest/compose.html#compose-composedetails
Anyway, as we saw, there is no need to get the body since the same API offers `isPlainText`.

All the questions here should have been posted to Thunderbird's add-on developers mailing list at addons@thunderbird.topicbox.com.

Anyway, one upon a time a guy pulled all extensions available on ATN and put them into a big repo:
https://cleidigh.github.io/ThunderKdB/. The like "code library" takes you here: https://github.com/cleidigh/ThunderKdB/tree/master/xall. And if you search for `getComposeDetails`, which is the function you need to call but don't know how, you get to:
https://github.com/search?q=repo%3Acleidigh%2FThunderKdB%20getComposeDetails&type=code

Looking at one of the search hits
https://github.com/cleidigh/ThunderKdB/blob/df0836af38a2b823790b093cda95671fe6a3e6b5/xall/x68/987734-mail-merge-p/src/content/thunderbird-iframe-service.js#L99
you can see code that gets that tab id:
https://github.com/cleidigh/ThunderKdB/blob/df0836af38a2b823790b093cda95671fe6a3e6b5/xall/x68/987734-mail-merge-p/src/content/thunderbird-iframe-service.js#L16

I'm not an add-on developer, but there are plenty hanging out on that mailing list. If you describe your problem briefly and concisely, you will likely get an answer. Something like:

---

I'm using 
```
browser.composeScripts.register({
  css: [],
  js: [{ file: 'compose.js' }]
});
```
in the background script to get my script loaded into the compose window. In that script, I like to work out whether I'm in a HTML or plaintext composition, ideally calling `getComposeDetails`. Where do I get the `tabId` parameter from? I saw that in Mail Merge a listener for `browser.runtime.onMessage` is added to capture arriving compose windows. Is there another way?

---

All that said, if you look at a plaintext composition you see this `<body style="font-family: -moz-fixed; white-space: pre-wrap; width: 72ch;">`. The width will change based on a pref. So if you find the fixed font and the pre-wrap, you can be pretty certain that you're in a plaintext composition.

**Comment by GrantEdwards** [comment]
> There is a misunderstanding here. I never suggested that the document would be anything but HTML, that's why I said in [#2 (comment)](https://github.com/GrantEdwards/CustomCSS/issues/2#issuecomment-1741784408): _"You could just get the body and check whether it's **HTML for a plaintext** composition with stuff like pre-wrap or so or a "normal" HTML composition"_.

You're right. I misread that as "check whether it's HTML **_or_** a plaintext..."

> _"get the compose body"_ was referring to this API/data structure which delivers the `body`. I was on the phone before and there I can't write lengthy comments with references: https://webextension-api.thunderbird.net/en/latest/compose.html#compose-composedetails Anyway, as we saw, there is no need to get the body since the same API offers `isPlainText`.

As described in the message you quoted, getting the compose details is complicated: you have to use the background script to attach handlers to one or more items in the UI so that you can grab tab IDs (which don't seem to be visible to compose/content scripts).  Checking the body elements style is orders of magnitude simler, so that's what I decided to do.




> All the questions here should have been posted to Thunderbird's add-on developers mailing list at [addons@thunderbird.topicbox.com](mailto:addons@thunderbird.topicbox.com).
> 
> Anyway, one upon a time a guy pulled all extensions available on ATN and put them into a big repo: https://cleidigh.github.io/ThunderKdB/. The like "code library" takes you here: https://github.com/cleidigh/ThunderKdB/tree/master/xall. 

Brilliant, thanks!

I manually downloaded and search 15 extensions that had "compose" in the name/description and found a couple examples, that all used click handlers in the background script.

**Comment by GrantEdwards** [comment]
Version 1.2 should fix this issue by leaving plaintext message unaccosted.

**Comment by Betterbird** [comment]
> As described in the message you quoted, getting the compose details is complicated: you have to use the background script to attach handlers to one or more items in the UI so that you can grab tab IDs (which don't seem to be visible to compose/content scripts). Checking the body elements style is orders of magnitude simler, so that's what I decided to do.

The question should still be asked on the addons@thunderbird.topicbox.com mailing list. It's cool that you can inject script into the compose window, but what can you find out about your environment while inside the script? Getting the compose details appears to be the most logical thing that you'd want to do. Or perhaps there's a completely different overall structure envisaged by the ones who designed the API.

**Comment by Betterbird** [comment]
Sorry, but you ignored what I wrote and now your change won't work if someone sets pref `mailnews.wraplength` to a value other than 72. I wrote here: https://github.com/GrantEdwards/CustomCSS/issues/2#issuecomment-1741825743:
**The width will change based on a pref.**

**Comment by GrantEdwards** [comment]
My bad. I missed that that width is configurable.  

I will ask on the addons topicbox forum about obtaining compose details from a compose script.

Thanks for all the pointers.
